# Generated by Django 4.2.7 on 2024-06-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="s3_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
