# Generated by Django 4.2.7 on 2024-06-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videoapp", "0002_video_s3_key"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="s3_key",),
    ]
